//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_40_wpf_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class gametable
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public Nullable<int> GamePrice { get; set; }
        public string GameRating { get; set; }
        public Nullable<bool> GameBought { get; set; }
    }
}
