//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_38_rabbits_advanced
{
    using System;
    using System.Collections.Generic;
    
    public partial class rabbittable
    {
        public int RabbitTableID { get; set; }
        public string RabbitName { get; set; }
        public Nullable<int> RabbitAge { get; set; }
        public Nullable<System.DateTime> RabbitDOB { get; set; }
        public Nullable<bool> RabbitIsActive { get; set; }
        public string RabbitType { get; set; }
    }
}
